vim_plugin_task "nerdtree-sl", "git://github.com/scrooloose/nerdtree.git"
vim_plugin_task "bundler", "git://github.com/tpope/vim-bundler.git"
vim_plugin_task "vim-rake", "git://github.com/tpope/vim-rake.git"
vim_plugin_task "ruby-sinatra", "git://github.com/hallison/vim-ruby-sinatra.git"
vim_plugin_task "autoclose", "git://github.com/Townk/vim-autoclose.git"
vim_plugin_task "jade", "git://github.com/digitaltoad/vim-jade.git"
vim_plugin_task "extradite", "git://github.com/int3/vim-extradite.git"
skip_vim_plugin "nerdtree"
skip_vim_plugin "arduino"
skip_vim_plugin "scala"
skip_vim_plugin "puppet"
skip_vim_plugin "snipmate"
skip_vim_plugin "searchfold"
skip_vim_plugin "textile"
